add delay to panning
interglobalvision/principled-design-com pull request #19
Opened 2017-05-22 04:12 UTC by mixcas

2017-05-23 18:11 UTC, varffs requested changes
Works fine but needs better variable name and also I think you should commit built files each time. Weird to have to run gulp on the branch to make it correct

2017-05-23 18:11 UTC, varffs commented on src/js/main.js
> +  delay: 100, // in ms
delay of what tho?

2017-05-24 01:24 UTC, mixcas commented
Will fix 

@varffs sorry about the built files, i feel i been committing them. Ill pay more attention next time.

2017-05-25 13:17 UTC, mixcas commented
This is ready. Also, @varffs all 3 commits include built files. Might be a problem on your side.

2017-05-25 18:15 UTC, varffs approved these changes

2017-05-25 18:17 UTC, merged