Feat ip location
interglobalvision/principled-design-com pull request #20
Opened 2017-05-23 08:12 UTC by mixcas

Theres a new field in Theme Options, the api key was sent to globie email.
Fixed some linting too.

2017-05-23 17:23 UTC, mikeyrayvon commented
i think `geolocation()` should be in `Site.Geolocation`, because later we will need to put the initial location into the `#lat-long` elem (found in `partials/map.php`) and update that displayed latlong as user moves around the map.

2017-05-23 17:24 UTC, mikeyrayvon commented
so as there is a bit more to it than just getting the initial location and positioning it, i think it should have its own space. agree or nah?

2017-05-23 18:05 UTC, varffs requested changes
Needs conditionals in the PHP. Needs real data in the JS. I agree with @mikeyrayvon on the refactor. Also the experience of the loading and moving to the geolocation thing is bad as the jump feels wrong. Either the map should wait to show until after the move, or the move should be animated and visually related to the geolocation text. (Also that text needs to be from real data too!)

2017-05-23 18:05 UTC, varffs commented on lib/dbip-client.class.php
> +<?php
could this be installed via Composer?

2017-05-23 18:05 UTC, varffs commented on lib/functions-custom.php
> +  $api_key = IGV_get_option('_igv_site_options', '_igv_dbip_api_key');
You need to check for this first. I think it causes a critical failure if this value is not set.

2017-05-23 18:05 UTC, varffs commented on lib/functions-custom.php
> +  $api_key = IGV_get_option('_igv_site_options', '_igv_dbip_api_key');
Yes it def causes a failure of the entire theme

2017-05-23 18:05 UTC, varffs commented on src/js/main.js
> +    // THIS IS FOR DEVELOPING WHILE WE GET THE REAL API KEY
why is this in the branch? We have an API key

2017-05-24 01:08 UTC, mixcas commented on lib/dbip-client.class.php
> +<?php
no ;(

2017-05-24 01:08 UTC, mixcas commented on lib/functions-custom.php
> +  $api_key = IGV_get_option('_igv_site_options', '_igv_dbip_api_key');
word

2017-05-24 01:09 UTC, mixcas commented on src/js/main.js
> +    // THIS IS FOR DEVELOPING WHILE WE GET THE REAL API KEY
cuz when i was working we didnt have one…?

2017-05-24 01:09 UTC, mixcas commented on src/js/main.js
> +    // THIS IS FOR DEVELOPING WHILE WE GET THE REAL API KEY
actually. the one we had was globie one, free plan. free plan doesnt return lat long. thats why

2017-05-24 01:28 UTC, mixcas commented
I agree with the missing conditionals in php and some bits in js.

About refactoring to it own object. I disagree. IMO [getting geolocation and moving the map to the matching position] is one feature and [geolocation indicator updating with coordinates matching the map position] is a diff feature and should be handled in a diff branch and definitely different object.

Also the [coordinates indicator] should be event driven. so whenever `moveMap` ocurres an `movemap` event is triggered . This is was is cleaner code, better performance and we don't have to worry about setting the initial coordinates in the indicator "manually".

2017-05-24 15:28 UTC, varffs commented
Ok fine to spec this feature as just that, but if so I think you need to name your PR a bit tighter or point out in the description the scope of it. Important to clean this asap as it is therefore blocking the rest of the geolocation features

2017-05-24 15:31 UTC, mixcas commented
I'm just getting to bed. If someone else could finish this would be the best.

2017-05-24 15:58 UTC, varffs approved these changes

2017-05-25 03:40 UTC, mikeyrayvon commented
this puts me at the center of the map. maybe this needs some error handling?

2017-05-25 13:46 UTC, mixcas reviewed
Fine except those pseudo boolean strings. What's the reason for this approach?

2017-05-25 13:46 UTC, mixcas commented on lib/functions-custom.php
> +    return '0';
Why return string here instead of false?

2017-05-25 13:46 UTC, mixcas commented on src/js/main.js
> +    if (WP.clientGeolocation === '0') {
Why string? x2

2017-05-25 13:46 UTC, mixcas commented on src/js/main.js
> +    if (WP.clientGeolocation === '0') {
If we `return false` from the php we can check for `WP.clientGeolocation == false` here

2017-05-25 17:00 UTC, mixcas commented
@mikeyrayvon We need the paid api key to get lat/long otherwise the free one doesnt return those values

2017-05-25 18:09 UTC, varffs commented on src/js/main.js
> +    if (WP.clientGeolocation === '0') {
I guess I wasn't sure about that due to the PHP>JS thing, but I'll test and change if it works

2017-05-25 18:10 UTC, varffs commented
Yh I didn't realise when I did my edits that the current key was only test so assumed it was going to work. Atm the returned values from the API don't include latlong. We could wait to merge this but I think should just do it now and fix any issues if they arrise with the real API. (I assumed @mixcas knew the response was going to have the `latitude` property named as he had used in testing)

2017-05-25 18:28 UTC, varffs commented
Well as I thought returning false from the PHP `false` return doesn't exactly translate into the JS. The JS actually ends up returning a empty string, but that reads as false with JS so the final outcome is cleaner code

2017-05-25 20:04 UTC, mikeyrayvon commented
Paid API Key:
a82de32adcadd64016832aa0d242ad460fe97b49

2017-05-25 20:17 UTC, mikeyrayvon commented
had to sign in to github at lumen to delete that comment. but api key is in trello card lol

2017-05-25 22:14 UTC, varffs requested changes
I'm not sure the solution. Either refactoring Minimap in a quick way or a complex way. Or a hack for the moment. or?

2017-05-25 22:14 UTC, varffs commented on src/js/main.js
> +      _this.moveMap(newX,newY);
this function `moveMap()` calls `Site.Minimap.moveIndicator()` but does so before the Minimap object has been initialized. That `moveIndicator()` function fails as it references something cached in the init function which hasn't happened. This breaks all the js. This also relates to what @mixcas was talking about in #17

2017-05-25 22:15 UTC, varffs commented on src/js/main.js
> +      _this.moveMap(newX,newY);
This is the line that causes the issue: https://github.com/interglobalvision/principled-design-com/blob/master/src/js/main.js#L614

2017-05-25 23:29 UTC, mixcas commented on src/js/main.js
> +      _this.moveMap(newX,newY);
@varffs Yeah, this is exactly what i am talking about in https://github.com/interglobalvision/principled-design-com/issues/17

This error you are talking about is not happening to me tho. Maybe is a problem with your built files? How about you @mikeyrayvon ?

2017-05-25 23:32 UTC, mixcas commented on src/js/main.js
> +      _this.moveMap(newX,newY);
Ah sorry. I didn't pull.

@varffs you fucked it in the merge. I will fix it

Why did u you merge and pull anyway?

2017-05-25 23:39 UTC, mixcas commented
@varffs i really don't get why u merged and push

2017-05-25 23:44 UTC, merged

2017-05-26 12:27 UTC, varffs commented on src/js/main.js
> +      Site.Map.init();
Why did you revert this? Minimap depends on Map and should be init after anyway?

2017-05-26 12:28 UTC, varffs commented on src/js/main.js
> +      _this.moveMap(newX,newY);
Was trying to make it a one button press for someone to speed it up

2017-05-27 04:51 UTC, mixcas commented on src/js/main.js
> +      Site.Map.init();
Cuz otherwise it wasn't working. I was thinking we should move the `window` object from `Site.Map` into just `Site`