Update patterns
interglobalvision/principled-design-com pull request #8
Opened 2017-05-12 00:54 UTC by mikeyrayvon

As I understand it from my meeting with Chris, this is the type of animation they want to see. Flashing thru each svg as you move. I told him about having a slow transition instead, and he said he might like that better, but wants to see this first.

2017-05-12 11:06 UTC, varffs requested changes
@mixcas need to check this relating to his custom events on the panning function

2017-05-12 11:06 UTC, varffs commented on dist/static/patterns/pattern-1.svg
> +<svg id="pattern-1" class="map-pattern" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2709.66 2709.66"><path class="a" d="M604.83 304.83v-300l300 300h-300zM304.83 304.83h-300l300-300v300zM604.83 30
maybe we need to improve the svgo config for gulp-imagemin but I think these should still go in src and be build into dist

2017-05-12 11:06 UTC, varffs commented on partials/map.php
> +      echo url_get_contents(get_template_directory_uri() . '/dist/static/patterns/pattern-1.svg');
we could upstream the improvement to this function from the starterpack (currently in a PR)

2017-05-12 11:06 UTC, varffs commented on src/js/main.js
> +    _this.showPattern();
I want @mixcas to look at this as I think his intention was to have this stuff happen separately bound to his custom events. I would favor separating the movement and the background changing.

2017-05-12 11:06 UTC, varffs commented on src/js/main.js
> +    $('svg#pattern-' + _this.currentPattern).addClass('show');
tag qualify isn't needed

2017-05-12 11:06 UTC, varffs commented on src/js/main.js
> +    $('.map-pattern').removeClass('show');
`$('.map-pattern')` gets hit a lot so is best cached

2017-05-12 11:06 UTC, varffs commented on src/js/main.js
> +    $('svg#pattern-' + _this.currentPattern).addClass('show');
you could also cache each of the pattern objects in an array and use the index of the array rather than the string addition style like this

2017-05-12 15:09 UTC, mikeyrayvon commented on dist/static/patterns/pattern-1.svg
> +<svg id="pattern-1" class="map-pattern" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2709.66 2709.66"><path class="a" d="M604.83 304.83v-300l300 300h-300zM304.83 304.83h-300l300-300v300zM604.83 30
i didnt know svgo was in the gulp

2017-05-12 15:10 UTC, mikeyrayvon commented on dist/static/patterns/pattern-1.svg
> +<svg id="pattern-1" class="map-pattern" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2709.66 2709.66"><path class="a" d="M604.83 304.83v-300l300 300h-300zM304.83 304.83h-300l300-300v300zM604.83 30
its not...

2017-05-12 15:11 UTC, mikeyrayvon commented on dist/static/patterns/pattern-1.svg
> +<svg id="pattern-1" class="map-pattern" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2709.66 2709.66"><path class="a" d="M604.83 304.83v-300l300 300h-300zM304.83 304.83h-300l300-300v300zM604.83 30
i dont see why this is a problem

2017-05-12 15:16 UTC, mikeyrayvon commented on src/js/main.js
> +    $('.map-pattern').removeClass('show');
k

2017-05-12 15:16 UTC, mikeyrayvon commented on src/js/main.js
> +    $('svg#pattern-' + _this.currentPattern).addClass('show');
good idea

2017-05-12 15:16 UTC, mikeyrayvon commented on src/js/main.js
> +    $('svg#pattern-' + _this.currentPattern).addClass('show');
k

2017-05-12 15:17 UTC, mikeyrayvon commented on partials/map.php
> +      echo url_get_contents(get_template_directory_uri() . '/dist/static/patterns/pattern-1.svg');
or we could keep it like this

2017-05-12 15:24 UTC, varffs commented on dist/static/patterns/pattern-1.svg
> +<svg id="pattern-1" class="map-pattern" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2709.66 2709.66"><path class="a" d="M604.83 304.83v-300l300 300h-300zM304.83 304.83h-300l300-300v300zM604.83 30
gulp-imagemin is just a stack for the 4 different npm modules including svgo https://www.npmjs.com/package/gulp-imagemin but I think we need to set the default config to not strip IDs at that is often the issue there. Lets leave for now but we should fix the starterpack so we can use src for svgs easily

2017-05-12 15:25 UTC, varffs commented on partials/map.php
> +      echo url_get_contents(get_template_directory_uri() . '/dist/static/patterns/pattern-1.svg');
not suggesting changing this code but rather bringing in these improvements to `url_get_contents` https://github.com/interglobalvision/globie-wordpress-starter-pack/pull/112

2017-05-12 15:26 UTC, mikeyrayvon commented on partials/map.php
> +      echo url_get_contents(get_template_directory_uri() . '/dist/static/patterns/pattern-1.svg');
oh the error handling stuff yea.  probably should

2017-05-12 15:27 UTC, mikeyrayvon commented on partials/map.php
> +      echo url_get_contents(get_template_directory_uri() . '/dist/static/patterns/pattern-1.svg');
but make an issue and deal with it  out of this branch

2017-05-12 15:33 UTC, mikeyrayvon commented on dist/static/patterns/pattern-1.svg
> +<svg id="pattern-1" class="map-pattern" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2709.66 2709.66"><path class="a" d="M604.83 304.83v-300l300 300h-300zM304.83 304.83h-300l300-300v300zM604.83 30
i didnt realize svgo was in that

2017-05-13 01:50 UTC, mixcas requested changes
On my local the background just flickers on yellow really fast. Is that how it's supposed to be? I know that's exactly what the code is doing but is that what they/we want?

I definitely think the background code should be on its own.

Code needs comments.

Also, just as a suggestion, I've been avoiding using jQuery where possible, specially for selectors. I feel theres no real advantage on using jQuery for selecting elements besides typing 10-15 letters more once. Most of the time we cache these selectors so they only appear once in the code. I feel now a days the only thing I appreciate from jQuery are the animation funcitons like `fadeIn()` and such.  I feel the code is way more readable without jQuery too.

2017-05-13 01:50 UTC, mixcas commented on src/js/main.js
> +    $('svg#pattern-' + _this.currentPattern).addClass('show');
whats tag qualify? the `svg` tag?

2017-05-13 01:50 UTC, mixcas commented on src/js/main.js
> +    $('.map-pattern').removeClass('show');
agreed, also i been avoiding jquery where possible, especially for selecting elements. tbh i feel the only thing i appreciate from jquery now a days are the animations functions, like `fadeIn()`. this is just a suggestion.

2017-05-13 01:50 UTC, mixcas commented on src/js/main.js
> +    _this.changePattern();
Yeah, i think we should manage this *background* functionality in it's own code, perhaps `Site.Background`. This way we keep every part clean and isolated. 
To bound to the events is as easy as:

```
document.querySelector('#map').addEventListener('stoppan', function() { console.log('stop');});
document.querySelector('#map').addEventListener('startpan', function() { console.log('start');});
```

I favor this approach cuz also we need those events to play/stop the videos around the map when they are on/off screen.

2017-05-15 13:27 UTC, mixcas commented
Also comments throughout the code would be great

2017-05-16 16:50 UTC, mikeyrayvon commented
flickering on yellow really fast? It should be animated through the 5 frames without a delay. The shape style is randomly selected onload as either yellow stroke or yellow fill.

2017-05-16 17:53 UTC, mikeyrayvon commented
thats what they requested

2017-05-17 12:57 UTC, varffs approved these changes

2017-05-17 12:57 UTC, varffs commented on src/js/main.js
> +    document.querySelector('#map').addEventListener('startpan', function() {
obv this code is fine and correct so this comment is about jquery vs vanilla convo: 

yh I don't really see the point in not writing jquery. this is just long and not as clean as a nice jquery `.on` with an event map. the perf issues dont really exist in this example as the querySelector has to run twice (could be cached tho) and then bind to the event. if this query was happening a lot then maybe the perf bump would have some effect.

the jquery equivalent is:

```
$('#map').on({
  'startpan': function() {...},
  'stoppan': function() {...},
});
```

which I def prefer

2017-05-17 12:57 UTC, varffs commented on src/js/main.js
> +    if (!_this.animating) {
not for this branch but maybe we should write the animation in another object together with the pan animation?

2017-05-17 12:57 UTC, varffs commented on src/styl/responsive/mobile.styl
> +  #background-pattern-holder svg
why are these rules needed?

2017-05-17 12:58 UTC, varffs commented
down to you @mixcas to hit the button. (or maybe you want to just do it @mikeyrayvon on my review alone if you need to press on?)

2017-05-18 00:31 UTC, mixcas commented on src/js/main.js
> +    if (!_this.animating) {
Like `Site.Animation.Map`, `Site.Animation.Pan`? That's a lil too much

2017-05-18 00:54 UTC, merged